from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ExecutionArtifact(BaseModel):
    """Artifact generated by a Business Agent execution."""

    model_config = ConfigDict(extra="forbid")

    artifact_id: str = Field(min_length=1)
    artifact_type: str = Field(min_length=1)
    name: str = Field(min_length=1)
    media_type: str = "application/json"
    uri: str | None = None
    content: Any | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)
